# Generated by Django 3.2 on 2022-03-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_slug'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='property.Property'),
        ),
    ]
