# Generated by Django 3.2 on 2022-04-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Client'), (3, 'Agent')], default=2),
        ),
    ]
