# Generated by Django 3.2 on 2022-03-13 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0002_alter_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.neighborhood'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='property.property'),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
