# Generated by Django 3.2 on 2022-03-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20220313_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.IntegerField(),
        ),
    ]
